CREATE TABLE users (
    id VARCHAR(8) PRIMARY KEY NOT NULL,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(320) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    removed BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE news_categories (
    id VARCHAR(8) PRIMARY KEY NOT NULL,
    name VARCHAR(150) NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    removed BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE news (
    id VARCHAR(8) PRIMARY KEY NOT NULL,
    category_id VARCHAR(8) NOT NULL REFERENCES news_categories(id) ON DELETE CASCADE,
    title VARCHAR(100) NOT NULL,
    subtitle VARCHAR(150),
    content TEXT NOT NULL,
    image_url TEXT NOT NULL,
    draft BOOLEAN DEFAULT TRUE NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    removed BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE groups (
    id VARCHAR(8) PRIMARY KEY NOT NULL,
    name VARCHAR(150) NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    removed BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE monitors (
    id VARCHAR(8) PRIMARY KEY NOT NULL,
    group_id VARCHAR(8) REFERENCES groups(id) ON DELETE CASCADE,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(320) NOT NULL UNIQUE,
    phone_number VARCHAR(20) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    ra VARCHAR(8) NOT NULL UNIQUE,
    subject VARCHAR(100) NOT NULL,
    period INTEGER NOT NULL CHECK (period BETWEEN 1 AND 10),
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    removed BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE team_members (
    id VARCHAR(8) PRIMARY KEY NOT NULL,
    group_id VARCHAR(8) REFERENCES groups(id) ON DELETE CASCADE,
    name VARCHAR(150) NOT NULL,
    ra VARCHAR(8) NOT NULL UNIQUE,
    image BYTEA,
    linkedin_url TEXT,
    role_name VARCHAR(100) NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    removed BOOLEAN DEFAULT FALSE NOT NULL
);